#pragma once

#define DEFAULT_LAYER_RGB_MATRIX    RGB_MATRIX_SOLID_REACTIVE
#define EXT_LAYER_RGB_MATRIX        RGB_MATRIX_CYCLE_SPIRAL
#define CFG_LAYER_RGB_MATRIX        RGB_MATRIX_STARLIGHT_DUAL_HUE

#ifdef RGB_MATRIX_ENABLE
#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_DEFAULT_MODE     DEFAULT_LAYER_RGB_MATRIX
#define RGB_MATRIX_STARTUP_MODE     DEFAULT_LAYER_RGB_MATRIX
#define TAPPING_TOGGLE              2
#endif


