#pragma once

#define MAIN_EFFECT RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define MOD_EFFECT  RGB_MATRIX_BAND_PINWHEEL_SAT

#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_KEYPRESSES

#define RGB_MATRIX_DEFAULT_MODE                     MAIN_EFFECT
#define RGB_MATRIX_STARTUP_MODE                     MAIN_EFFECT

#define RGB_MATRIX_TYPING_HEATMAP_INCREASE_STEP 40
#define RGB_MATRIX_TYPING_HEATMAP_AREA_LIMIT 20
#define RGB_MATRIX_TYPING_HEATMAP_SPREAD 48
#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 100

#endif
